<form action="<?php echo $action; ?>" method="post">
 
 
 
 
<input type="hidden" name="oid" value="<?php echo $cart_order_id; ?>" /> 
  <input type="hidden" name="site_redirect_url" value="<?php echo $callback; ?>" /> 
  
 
  
  <div class="buttons">
    <div class="right">
      <input type="submit" value="<?php echo $button_confirm; ?>" class="button btn btn-primary" />
    </div>
  </div>
</form>
