<?php $this->headStyle()->captureStart();?>
.formDropdown {
width: 100%;
}
<?php $this->headStyle()->captureEnd();?>
	<? $this->layout('layout/templates/'.TID.'/default'); ?>
		<!-- Begin Main -->
		<div role="main" class="main">
		
			
			
			<div class="container" style="margin-top:40px">
				<div class="row">
					<div class="col-md-3 hidden-xs hidden-sm">
						 
							<aside class="block blk-cat">
							 
								
								
								
								  <?php if ($categories) { ?>
  <h4>Sub Categories</h4>
 
    <?php if (count($categories) <= 5) { ?>
    <ul  class="list-unstyled list-cat">
      <?php foreach ($categories as $category) { ?>
      <li><a href="<?php echo $category['href']; ?>"><?php echo $category['name']; ?></a></li>
      <?php } ?>
    </ul>
    <?php } else { ?>
    <?php for ($i = 0; $i < count($categories);) { ?>
    <ul>
      <?php $j = $i + ceil(count($categories) / 4); ?>
      <?php for (; $i < $j; $i++) { ?>
      <?php if (isset($categories[$i])) { ?>
      <li><a href="<?php echo $categories[$i]['href']; ?>"><?php echo $categories[$i]['name']; ?></a></li>
      <?php } ?>
      <?php } ?>
    </ul>
    <?php } ?>
    <?php } ?> 
  <?php } ?>
								 <h4>Categories</h4>
								    <ul class="box-category list-unstyled list-cat">
      <?php foreach ($side_categories as $category) { ?>
      <li>
        <?php if ($category['category_id'] == $category_id) { ?>
        <a href="<?php echo $category['href']; ?>" class="active"><?php echo $category['name'];  ?></a>
        <?php } else { ?>
        <a href="<?php echo $category['href']; ?>"><?php echo $category['name']; ?></a>
        <?php } ?>
        <?php if ($category['children']) { ?>
        <ul class="list-unstyled list-cat">
          <?php foreach ($category['children'] as $child) { ?>
          <li>
            <?php if ($child['category_id'] == $child_id) { ?>
            <a href="<?php echo $child['href']; ?>" class="active"> - <?php echo $child['name']; ?></a>
            <?php } else { ?>
            <a href="<?php echo $child['href']; ?>"> - <?php echo $child['name']; ?></a>
            <?php } ?>
          </li>
          <?php } ?>
        </ul>
        <?php } ?>
      </li>
      <?php } ?>
    </ul>
							</aside>
						
						 <?php echo $column_left; ?><?php echo $column_right; ?>
					</div>
					<div class="col-md-9">
						<!-- Begin Lookbook Women -->
						<section id="lookbook">
							<div class="lookbook">
								<h2><a href="#"><?php echo $heading_title; ?></a></h2>
								<?php if ($thumb || $description) { ?>
								<p>
								
								 <?php if ($thumb) { ?>
    <div class="image"><img src="<?php echo $thumb; ?>" alt="<?php echo $heading_title; ?>" /></div>
    <?php } ?>
    <?php if ($description) { ?>
    <?php echo $description; ?>
    <?php } ?>
								</p>
								<?php } ?>
							</div>
						</section>
						<!-- End Lookbook Women -->
						
						<div class="catalog">
							<div class="toolbar clearfix row">
							<div class="col-xs-6">
								<p class="pull-left"><?php echo $paginationObject->outputText?></p>
							</div>
								
								<div class="col-xs-3">
								<!-- Ordering -->
								<div class="list-sort " >
									<select class="formDropdown"  onchange="location = this.value;">
										 
										    <?php foreach ($limits as $limits) { ?>
								        <?php if ($limits['value'] == $limit) { ?>
								        <option value="<?php echo $limits['href']; ?>" selected="selected"><?php echo $limits['text']; ?></option>
								        <?php } else { ?>
								        <option value="<?php echo $limits['href']; ?>"><?php echo $limits['text']; ?></option>
								        <?php } ?>
								        <?php } ?>
									</select>
								</div>
								
								</div>
								
								<div class="col-xs-3">
								<div class="list-sort">
									<select onchange="location = this.value;" class="formDropdown">
										 
										 
									        <?php foreach ($sorts as $sorts) { ?>
									        <?php if ($sorts['value'] == $sort . '-' . $order) { ?>
									        <option value="<?php echo $sorts['href']; ?>" selected="selected"><?php echo $sorts['text']; ?></option>
									        <?php } else { ?>
									        <option value="<?php echo $sorts['href']; ?>"><?php echo $sorts['text']; ?></option>
									        <?php } ?>
									        <?php } ?>
									     
									</select>
								</div>
								</div>
							
							
							</div>
							<?php $counter = 2;?>
							 <?php foreach ($products as $product) { $counter++; ?>
							 
							 <?php if(($counter % 3)==0):?>
							<div class="row">
							<?php endif;?>
							
								<div class="col-xs-4">
									<div class="product">
										<div class="product-thumb-info">
											<div class="product-thumb-info-image">
												<span class="product-thumb-info-act">
													<a href="<?php echo $product['href']; ?>" class="view-product">
														<span><i class="fa fa-external-link"></i></span>
													</a>
													<a href="javascript:;" onclick="addToCart('<?php echo $product['product_id']; ?>');"  class="add-to-cart-product">
														<span><i class="fa fa-shopping-cart"></i></span>
													</a>
												</span>
												<img alt="" class="img-responsive" src="<?php echo $product['thumb']; ?>">
											</div>
											<div class="product-thumb-info-content">
												<span class="price pull-right">
												
												 
											        <?php if (!$product['special']) { ?>
											        <?php echo $product['price']; ?>
											        <?php } else { ?>
											        <span class="price-old"><?php echo $product['price']; ?></span> <span class="price-new"><?php echo $product['special']; ?></span>
											        <?php } ?>
											       
											     
												
												
												</span>
												<h4><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></h4>
												<span class="item-cat pull-right"><small>
												 <?php if ($product['tax']) { ?> 
											        <span class="price-tax"><?php echo $text_tax; ?> <?php echo $product['tax']; ?></span>
											        <?php } ?>
												</small></span>
											</div>
										</div>
									</div>
								</div>
								
								
								
								
							 <?php if(( ($counter+1) % 3)==0):?>	
							</div>
							<?php endif;?>
							
							  <?php } ?>
							  
							   <?php if(( ($counter+1) % 3)!=0):?>	
							</div>
							<?php endif;?>
							  
							<ul class="pagination">								
								<?php foreach($paginationObject->outputLinksArray as $value):?>
								<li><a href="<?php echo $value['href']?>"><?php echo $value['text']?></a></li>
								<?php endforeach;?>
						   </ul>
					   </div>
					</div>
				</div>
				
				
			</div>
			
		</div>
		<!-- End Main -->