<!-- container 12 start -->
<!-- breadcrumb start -->
<div class="container_12 cf">
<div class="grid_12">
 
<div class="oc_breadcrumb">
 

	<?php $count = count($breadcrumbs); $counter=0;?>
							    <?php foreach ($breadcrumbs as $breadcrumb) { $counter++; ?>
							    
     <a <?php if($counter < $count):?>href="<?php echo $breadcrumb['href']; ?>" <?php else:?> href="#" class="current" <?php endif; ?> > <?php echo $breadcrumb['text']; ?> <?php if($counter < $count):?>   /  <?php endif; ?></a>
    <?php } ?>


</div>

</div>
</div>
<!-- breadcrumb end -->
<!-- container 12 end -->



    <?php if (@$attention) { ?>
<div class="attention" style="margin-left:20px; margin-right:20px" ><?php echo $attention; ?><img src="<?php echo $this->basePath(); ?>/static/oc_catalog/default/image/close.png" alt="" class="close" /></div>
<?php } ?>
<?php if (@$success) { ?>
<div class="success" style="margin-left:20px; margin-right:20px"><?php echo $success; ?><img src="<?php echo $this->basePath(); ?>/static/oc_catalog/default/image/close.png" alt="" class="close" /></div>
<?php } ?>
<?php if (@$error_warning) { ?>
<div class="warning" style="margin-left:20px; margin-right:20px"><?php echo $error_warning; ?><img src="<?php echo $this->basePath(); ?>/static/oc_catalog/default/image/close.png" alt="" class="close" /></div>
<?php } ?>


<!-- container 12 start -->
<div class="container_12 cf">

<div class="grid_12">

<div class="headerbd">
<h1>Shopping Cart <?php if (@$weight) { ?>
    &nbsp;(<?php echo $weight; ?>)
    <?php } ?></h1>
<div class="header-bottom-line"></div>
</div>

					
    <?php if($cart->hasProducts()): ?>
  
  
  	<form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
    <div class="cart-info">
      <table>
        <thead>
          <tr>
            <td class="image">Image</td>
            <td class="name">Product Name</td>
            <td class="model">Model</td>
            <td class="quantity">Quantity</td>
            <td class="price">Unit Price</td>
            <td class="total">Total</td>
          </tr>
        </thead>
        <tbody>
              
                    
                    
                    
                    
                    
                    
                    
                  <?php foreach ($products as $product) { ?>
          <tr>
            <td  class="col_product"><div class="image"><?php if ($product['thumb']) { ?>
              <a href="<?php echo $product['href']; ?>"><img src="<?php echo $product['thumb']; ?>" alt="<?php echo $product['name']; ?>" title="<?php echo $product['name']; ?>" /></a>
              <?php } ?></div></td>
            <td class="name"><h5><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></h5>
              <?php if (!$product['stock']) { ?>
              <span class="stock">***</span>
              <?php } ?>
              <div>
                <?php foreach ($product['option'] as $option) { ?>
                - <small><?php echo $option['name']; ?>: <?php echo $option['value']; ?></small><br />
                <?php } ?>
              </div>
              <?php if ($product['reward']) { ?>
              <small><?php echo $product['reward']; ?></small>
              <?php } ?></td>
            <td class="model"><?php echo $product['model']; ?></td>
            <td class="quantity">
            <input class="w30" type="text" name="quantity[<?php echo $product['key']; ?>]" value="<?php echo $product['quantity']; ?>" size="1" />
              &nbsp;
              <input type="image" class="tooltip_s"  src="<?php echo $this->layoutPath(); ?>/images/update.png" alt="<?php echo $button_update; ?>" title="<?php echo $button_update; ?>" />
              &nbsp;<a class="trash tooltip_s" href="<?php echo $product['remove']; ?>" title="Remove"><img src="<?php echo $this->layoutPath(); ?>/images/remove.png" alt="<?php echo $button_remove; ?>" title="<?php echo $button_remove; ?>" /></a>
            
            
            
            
            
           </td>
            <td class="price"><?php echo $product['price']; ?></td>
            <td class="total"><?php echo $product['total']; ?></td>
          </tr>
          <?php } ?>
          <?php foreach ($vouchers as $vouchers) { ?>
          <tr>
            <td class="image"></td>
            <td class="name"><?php echo $vouchers['description']; ?></td>
            <td class="model"></td>
            <td class="quantity"><input   class="w30" type="text" name="" value="1" size="1" disabled="disabled" />
              &nbsp;<a  class="trash tooltip_s" href="<?php echo $vouchers['remove']; ?>"><img src="<?php echo $this->layoutPath(); ?>/images/remove.png" alt="<?php echo $button_remove; ?>" title="<?php echo $button_remove; ?>" /></a></td>
            <td class="price"><?php echo $vouchers['amount']; ?></td>
            <td class="total"><?php echo $vouchers['amount']; ?></td>
          </tr>
          <?php } ?>
              
              
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                            </tbody>
      </table>
    </div>
  </form>
  
    <?php if ($coupon_status || $voucher_status || $reward_status || $shipping_status) { ?>
  <h2><?php echo $text_next; ?></h2>
  <div class="content">
    <p><?php echo $text_next_choice; ?></p>
    <table class="radio">
      <?php if ($coupon_status) { ?>
      <tr >
        <td><?php if ($next == 'coupon') { ?>
          <input type="radio" name="next" value="coupon" id="use_coupon" checked="checked" />
          <?php } else { ?>
          <input type="radio" name="next" value="coupon" id="use_coupon" />
          <?php } ?></td>
        <td><label for="use_coupon"><?php echo $text_use_coupon; ?></label></td>
      </tr>
      <?php } ?>
      <?php if ($voucher_status) { ?>
      <tr  >
        <td><?php if ($next == 'voucher') { ?>
          <input type="radio" name="next" value="voucher" id="use_voucher" checked="checked" />
          <?php } else { ?>
          <input type="radio" name="next" value="voucher" id="use_voucher" />
          <?php } ?></td>
        <td><label for="use_voucher"><?php echo $text_use_voucher; ?></label></td>
      </tr>
      <?php } ?>
      <?php if ($reward_status) { ?>
      <tr >
        <td><?php if ($next == 'reward') { ?>
          <input type="radio" name="next" value="reward" id="use_reward" checked="checked" />
          <?php } else { ?>
          <input type="radio" name="next" value="reward" id="use_reward" />
          <?php } ?></td>
        <td><label for="use_reward"><?php echo $text_use_reward; ?></label></td>
      </tr>
      <?php } ?>
      <?php if ($shipping_status) { ?>
      <tr  >
        <td><?php if ($next == 'shipping') { ?>
          <input type="radio" name="next" value="shipping" id="shipping_estimate" checked="checked" />
          <?php } else { ?>
          <input type="radio" name="next" value="shipping" id="shipping_estimate" />
          <?php } ?></td>
        <td><label for="shipping_estimate"><?php echo $text_shipping_estimate; ?></label></td>
      </tr>
      <?php } ?>
    </table>
  </div>
  <div class="cart-module">
    <div id="coupon" class="content" style="display: <?php echo ($next == 'coupon' ? 'block' : 'none'); ?>;">
      <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
        <?php echo $entry_coupon; ?>&nbsp;
        <input   type="text" name="coupon" value="<?php echo $coupon; ?>" />
        <input type="hidden" name="next" value="coupon" />
        &nbsp;
        <input type="submit" value="<?php echo $button_coupon; ?>" class="button btn btn-primary btn-sm" />
      </form>
    </div>
    <div id="voucher" class="content" style="display: <?php echo ($next == 'voucher' ? 'block' : 'none'); ?>;">
      <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
        <?php echo $entry_voucher; ?>&nbsp;
        <input    type="text" name="voucher" value="<?php echo $voucher; ?>" />
        <input type="hidden" name="next" value="voucher" />
        &nbsp;
        <input type="submit" value="<?php echo $button_voucher; ?>" class="button btn btn-primary btn-sm" />
      </form>
    </div>
    <div id="reward" class="content" style="display: <?php echo ($next == 'reward' ? 'block' : 'none'); ?>;">
      <form action="<?php echo $action; ?>" method="post" enctype="multipart/form-data">
        <?php echo $entry_reward; ?>&nbsp;
        <input  type="text" name="reward" value="<?php echo $reward; ?>" />
        <input type="hidden" name="next" value="reward" />
        &nbsp;
        <input type="submit" value="<?php echo $button_reward; ?>" class="button btn btn-primary btn-sm" />
      </form>
    </div>
    <div id="shipping" class="content" style="display: <?php echo ($next == 'shipping' ? 'block' : 'none'); ?>;">
      <p><?php echo $text_shipping_detail; ?></p>
      <table>
        <tr>
          <td><span class="required">*</span> <?php echo $entry_country; ?></td>
          <td><select class="form-control"  name="country_id">
              <option value=""><?php echo $text_select; ?></option>
              <?php foreach ($countries as $country) { ?>
              <?php if ($country['country_id'] == $country_id) { ?>
              <option value="<?php echo $country['country_id']; ?>" selected="selected"><?php echo $country['name']; ?></option>
              <?php } else { ?>
              <option value="<?php echo $country['country_id']; ?>"><?php echo $country['name']; ?></option>
              <?php } ?>
              <?php } ?>
            </select></td>
        </tr>
        <tr>
          <td><span class="required">*</span> <?php echo $entry_zone; ?></td>
          <td><select class="form-control"  name="zone_id">
            </select></td>
        </tr>
        <tr>
          <td><span id="postcode-required" class="required">*</span> <?php echo $entry_postcode; ?></td>
          <td><input class="form-control" type="text" name="postcode" value="<?php echo $postcode; ?>" /></td>
        </tr>
      </table>
      <input type="button" value="<?php echo $button_quote; ?>" id="button-quote" class="button btn btn-primary btn-sm" />
    </div>
  </div>
  <?php } ?>
  

  
      
      
      
  <div class="cart-total">
    <table id="total">
          
         
      					<?php foreach ($totals as $total) { ?>
      					
      		   <tr>
        <td class="right"><b><?php echo $total['title']; ?></b></td>
        <td class="right"><span class="total-price"><?php echo $total['text']; ?></span></td>
      </tr>
      			
   
      <?php } ?>
          </table>
  </div>
  <div class="buttons">
    <div class="right"><a href="<?php echo $continue; ?>" class="sc_button medium orange">Continue Shopping</a> <a href="<?php echo $checkout; ?>" class="sc_button medium orange">Checkout</a></div>
  </div>

   <?php require_once DIR_TEMPLATE.'/store/checkout/cart/cart_footer.phtml'; ?>
<?php else: ?>

<div style="margin-bottom: 100px">
<h4>Your cart is empty</h4>
</div>

<? endif; ?>

</div>

</div>
<!-- container 12 end -->


