
<section class="page-top">
				<div class="container">
					<div class="page-top-in">
						<h2><span><?php echo $heading_title; ?></span></h2>
					</div>
				</div>
			</section>


 	<div class="container">
				<div class="row">
					<div class="col-md-9">
						<div class="blog-posts single-post">
							<article class="post post-large blog-single-post">
							 
							 
							 
								<div class="post-content">
								 <?php echo $description; ?>
								</div>
								
								<?php echo $content_bottom; ?>
								
							
							</article>
							
						</div>
					</div>
					<div class="col-md-3">
						<aside class="sidebar">
							<aside class="block">
							 <?php echo $column_left; ?><?php echo $column_right; ?>
							</aside>
							
						</aside>
					</div>
				</div>	
			
			
			
			
			
			
			
			</div>
			
	 
		<!-- End Main -->
		